name: railway_qr_tracker
description: Railway QR Tracker - Smart India Hackathon 2025
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.2

  # HTTP & Networking
  http: ^1.1.0
  dio: ^5.3.2
  connectivity_plus: ^5.0.2

  # QR Code functionality
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6

  # Navigation
  go_router: ^12.1.3

  # State Management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2

  # Utilities
  uuid: ^4.2.1
  equatable: ^2.0.5
  package_info_plus: ^4.2.0

  # Device Features (Note: Some may not work on web)
  vibration: ^1.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Remove problematic font assets for now
  # assets:
  #   - assets/images/
